//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainService.DataAccess.Repositories.Scripts {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MainService.DataAccess.Repositories.Scripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        internal static string CreateCourseType {
            get {
                return ResourceManager.GetString("CreateCourseType", resourceCulture);
            }
        }
        
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        internal static string DeleteCourseType {
            get {
                return ResourceManager.GetString("DeleteCourseType", resourceCulture);
            }
        }
        
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        internal static string GetCourseTypeById {
            get {
                return ResourceManager.GetString("GetCourseTypeById", resourceCulture);
            }
        }
        
        internal static string GetUserByEmailAndPassword {
            get {
                return ResourceManager.GetString("GetUserByEmailAndPassword", resourceCulture);
            }
        }
        
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        internal static string GetUserByRefreshToken {
            get {
                return ResourceManager.GetString("GetUserByRefreshToken", resourceCulture);
            }
        }
        
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        internal static string IsCourseTypeExistsById {
            get {
                return ResourceManager.GetString("IsCourseTypeExistsById", resourceCulture);
            }
        }
        
        internal static string IsUserExistsByEmail {
            get {
                return ResourceManager.GetString("IsUserExistsByEmail", resourceCulture);
            }
        }
        
        internal static string IsUserExistsByUsername {
            get {
                return ResourceManager.GetString("IsUserExistsByUsername", resourceCulture);
            }
        }
        
        internal static string IsUserExistsById {
            get {
                return ResourceManager.GetString("IsUserExistsById", resourceCulture);
            }
        }
        
        internal static string UpdateCourseType {
            get {
                return ResourceManager.GetString("UpdateCourseType", resourceCulture);
            }
        }
        
        internal static string UpdateRefreshToken {
            get {
                return ResourceManager.GetString("UpdateRefreshToken", resourceCulture);
            }
        }
        
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        internal static string GetCourseTypes {
            get {
                return ResourceManager.GetString("GetCourseTypes", resourceCulture);
            }
        }
        
        internal static string CreateCourse {
            get {
                return ResourceManager.GetString("CreateCourse", resourceCulture);
            }
        }
        
        internal static string DeleteCourse {
            get {
                return ResourceManager.GetString("DeleteCourse", resourceCulture);
            }
        }
        
        internal static string GetCourseById {
            get {
                return ResourceManager.GetString("GetCourseById", resourceCulture);
            }
        }
        
        internal static string GetCourses {
            get {
                return ResourceManager.GetString("GetCourses", resourceCulture);
            }
        }
        
        internal static string IsCourseExistsById {
            get {
                return ResourceManager.GetString("IsCourseExistsById", resourceCulture);
            }
        }
        
        internal static string UpdateCourse {
            get {
                return ResourceManager.GetString("UpdateCourse", resourceCulture);
            }
        }
        
        internal static string CreateModule {
            get {
                return ResourceManager.GetString("CreateModule", resourceCulture);
            }
        }
        
        internal static string DeleteModule {
            get {
                return ResourceManager.GetString("DeleteModule", resourceCulture);
            }
        }
        
        internal static string GetModuleById {
            get {
                return ResourceManager.GetString("GetModuleById", resourceCulture);
            }
        }
        
        internal static string GetModulesByCourseId {
            get {
                return ResourceManager.GetString("GetModulesByCourseId", resourceCulture);
            }
        }
        
        internal static string IsModuleExistsById {
            get {
                return ResourceManager.GetString("IsModuleExistsById", resourceCulture);
            }
        }
        
        internal static string UpdateModule {
            get {
                return ResourceManager.GetString("UpdateModule", resourceCulture);
            }
        }
        
        internal static string GetLastModuleOrder {
            get {
                return ResourceManager.GetString("GetLastModuleOrder", resourceCulture);
            }
        }
        
        internal static string ReorderModules {
            get {
                return ResourceManager.GetString("ReorderModules", resourceCulture);
            }
        }
        
        internal static string CreateLesson {
            get {
                return ResourceManager.GetString("CreateLesson", resourceCulture);
            }
        }
        
        internal static string DeleteLesson {
            get {
                return ResourceManager.GetString("DeleteLesson", resourceCulture);
            }
        }
        
        internal static string GetLessonById {
            get {
                return ResourceManager.GetString("GetLessonById", resourceCulture);
            }
        }
        
        internal static string GetLessonsByModuleId {
            get {
                return ResourceManager.GetString("GetLessonsByModuleId", resourceCulture);
            }
        }
        
        internal static string IsLessonExistsById {
            get {
                return ResourceManager.GetString("IsLessonExistsById", resourceCulture);
            }
        }
        
        internal static string UpdateLesson {
            get {
                return ResourceManager.GetString("UpdateLesson", resourceCulture);
            }
        }
        
        internal static string GetLastLessonOrder {
            get {
                return ResourceManager.GetString("GetLastLessonOrder", resourceCulture);
            }
        }
        
        internal static string ReorderLessons {
            get {
                return ResourceManager.GetString("ReorderLessons", resourceCulture);
            }
        }
    }
}
